controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

homepage:
    path: /homepage
    controller: App\Controller\HomeController::homeAction

app_logout:
    path: /logout
